// Phase 14 compat bridge.
export {
  VOICE_MAP,
  initVoiceBroadcast,
  getBusy,
  setBusy,
  getMuted,
  setMuted,
  getCurrentVoice,
  setCurrentVoice,
  getVoiceEnabled,
  setVoiceEnabled,
  getSuppressVoiceWakeUntilMs,
  setSuppressVoiceWakeUntilMs,
  createMicCapturePath,
  cleanupAudioArtifacts,
  recordMic,
  transcribe,
  stopSpeaking,
  speak,
  playThinking,
  normalizeRuntimeTone,
  runtimeToneDirective,
} from "../runtime/modules/audio/voice.js";
