export const COUNCIL_RULES = [
  {
    id: "memory-council",
    routeTokens: ["memory"],
    responseRouteTokens: ["memory"],
    textTokens: [],
  },
  {
    id: "planning-council",
    routeTokens: ["workflow", "mission"],
    responseRouteTokens: ["workflow", "mission"],
    textTokens: ["workflow", "mission", "schedule", "calendar", "plan"],
  },
  {
    id: "policy-council",
    routeTokens: ["policy", "approval", "authz"],
    responseRouteTokens: ["policy", "approval", "authz"],
    textTokens: ["policy", "approval", "compliance"],
  },
];

export const DEFAULT_COUNCIL_ID = "routing-council";

export const DOMAIN_WORKER_RULES = [
  {
    domainManagerId: "media-manager",
    workerAgentId: "spotify-agent",
    reason: "spotify_intent",
    routeTokens: ["spotify"],
    responseRouteTokens: ["spotify"],
    textTokens: ["spotify", "play music", "track", "playlist"],
    toolCallTokens: ["spotify"],
  },
  {
    domainManagerId: "media-manager",
    workerAgentId: "voice-agent",
    reason: "voice_control",
    routeTokens: [],
    responseRouteTokens: [],
    textTokens: ["voice mode", "microphone", "mic "],
    toolCallTokens: ["voice"],
  },
  {
    domainManagerId: "media-manager",
    workerAgentId: "tts-agent",
    reason: "tts_execution",
    routeTokens: [],
    responseRouteTokens: [],
    textTokens: ["speak", "read aloud", "text to speech"],
    toolCallTokens: ["tts"],
  },
  {
    domainManagerId: "finance-manager",
    workerAgentId: "coinbase-agent",
    reason: "coinbase_signal",
    routeTokens: [],
    responseRouteTokens: [],
    textTokens: ["coinbase", "portfolio", "wallet"],
    toolCallTokens: ["coinbase"],
  },
  {
    domainManagerId: "finance-manager",
    workerAgentId: "crypto-agent",
    reason: "crypto_signal",
    routeTokens: ["crypto"],
    responseRouteTokens: ["crypto"],
    textTokens: ["crypto", "btc", "eth", "sol"],
    toolCallTokens: ["crypto"],
  },
  {
    domainManagerId: "finance-manager",
    workerAgentId: "market-agent",
    reason: "market_or_weather_signal",
    routeTokens: ["weather"],
    responseRouteTokens: ["weather"],
    textTokens: ["weather", "market", "price"],
    toolCallTokens: ["weather", "market"],
  },
  {
    domainManagerId: "productivity-manager",
    workerAgentId: "missions-agent",
    reason: "mission_signal",
    routeTokens: ["workflow", "mission"],
    responseRouteTokens: ["workflow", "mission"],
    textTokens: ["mission", "workflow", "automation"],
    toolCallTokens: ["mission"],
  },
  {
    domainManagerId: "productivity-manager",
    workerAgentId: "calendar-agent",
    reason: "calendar_signal",
    routeTokens: [],
    responseRouteTokens: [],
    textTokens: ["calendar", "meeting", "reschedule"],
    toolCallTokens: ["calendar"],
  },
  {
    domainManagerId: "productivity-manager",
    workerAgentId: "reminders-agent",
    reason: "reminder_signal",
    routeTokens: [],
    responseRouteTokens: [],
    textTokens: ["reminder", "remind me"],
    toolCallTokens: ["reminder"],
  },
  {
    domainManagerId: "comms-manager",
    workerAgentId: "gmail-agent",
    reason: "gmail_signal",
    routeTokens: [],
    responseRouteTokens: [],
    textTokens: ["gmail", "email", "inbox"],
    toolCallTokens: ["gmail"],
  },
  {
    domainManagerId: "comms-manager",
    workerAgentId: "telegram-agent",
    reason: "telegram_signal",
    routeTokens: [],
    responseRouteTokens: [],
    textTokens: ["telegram"],
    toolCallTokens: ["telegram"],
  },
  {
    domainManagerId: "comms-manager",
    workerAgentId: "discord-agent",
    reason: "discord_signal",
    routeTokens: [],
    responseRouteTokens: [],
    textTokens: ["discord"],
    toolCallTokens: ["discord"],
  },
  {
    domainManagerId: "system-manager",
    workerAgentId: "web-research-agent",
    reason: "web_research_signal",
    routeTokens: [],
    responseRouteTokens: [],
    textTokens: ["search", "look up", "citation"],
    toolCallTokens: ["web_search", "web_fetch", "research"],
  },
  {
    domainManagerId: "system-manager",
    workerAgentId: "files-agent",
    reason: "file_memory_signal",
    routeTokens: ["memory"],
    responseRouteTokens: ["memory"],
    textTokens: [],
    toolCallTokens: ["file", "memory", "workspace"],
  },
  {
    domainManagerId: "system-manager",
    workerAgentId: "diagnostics-agent",
    reason: "diagnostic_signal",
    routeTokens: [],
    responseRouteTokens: [],
    textTokens: ["diagnostic", "debug", "trace", "health"],
    toolCallTokens: [],
  },
];

export const DEFAULT_DOMAIN_WORKER_RULE = {
  domainManagerId: "system-manager",
  workerAgentId: "diagnostics-agent",
  reason: "default_system_route",
};

export const PROVIDER_ADAPTER_BY_PROVIDER = {
  openai: "openai-adapter",
  claude: "claude-adapter",
  grok: "grok-adapter",
  gemini: "gemini-adapter",
  "openai-chatkit": "openai-adapter",
  none: "none",
};

