export const OPERATOR_LANE_SEQUENCE = [
  {
    id: "youtube",
    shouldRouteFlag: "shouldRouteToYouTube",
    directIntentFnKey: "isYouTubeDirectIntent",
    contextualFollowUpIntentFnKey: "isYouTubeContextualFollowUpIntent",
    shortTermFollowUpFlag: "youtubeShortTermFollowUp",
    followUpBlockedByDirectRouteId: "spotify",
    routeHint: "youtube",
    responseRoute: "youtube",
    toolCalls: ["youtube_home_control"],
    domainId: "youtube",
    resultRoute: "youtube",
    defaultTopicAffinityId: "youtube_general",
    executionMode: "youtube",
  },
  {
    id: "spotify",
    shouldRouteFlag: "shouldRouteToSpotify",
    directIntentFnKey: "isSpotifyDirectIntent",
    contextualFollowUpIntentFnKey: "isSpotifyContextualFollowUpIntent",
    shortTermFollowUpFlag: "spotifyShortTermFollowUp",
    routeHint: "spotify",
    responseRoute: "spotify",
    toolCalls: ["spotify"],
    domainId: "spotify",
    resultRoute: "spotify",
    defaultTopicAffinityId: "spotify_general",
    executionMode: "spotify",
  },
  {
    id: "image",
    shouldRouteFlag: "shouldRouteToImage",
    directIntentFnKey: "isImageDirectIntent",
    contextualFollowUpIntentFnKey: "isImageContextualFollowUpIntent",
    shortTermFollowUpFlag: "imageShortTermFollowUp",
    routeHint: "image",
    responseRoute: "image",
    toolCalls: ["image"],
    domainId: "image",
    resultRoute: "image",
    defaultTopicAffinityId: "image_general",
    executionMode: "image",
  },
  {
    id: "polymarket",
    shouldRouteFlag: "shouldRouteToPolymarket",
    directIntentFnKey: "isPolymarketDirectIntent",
    contextualFollowUpIntentFnKey: "isPolymarketContextualFollowUpIntent",
    shortTermFollowUpFlag: "polymarketShortTermFollowUp",
    routeHint: "polymarket",
    responseRoute: "polymarket",
    toolCalls: ["polymarket"],
    domainId: "polymarket",
    resultRoute: "polymarket",
    defaultTopicAffinityId: "polymarket_general",
    executionMode: "polymarket",
  },
  {
    id: "coinbase",
    shouldRouteFlag: "shouldRouteToCoinbase",
    directIntentFnKey: "isCoinbaseDirectIntent",
    contextualFollowUpIntentFnKey: "isCoinbaseContextualFollowUpIntent",
    shortTermFollowUpFlag: "coinbaseShortTermFollowUp",
    routeHint: "coinbase",
    responseRoute: "coinbase",
    toolCalls: ["coinbase"],
    domainId: "coinbase",
    resultRoute: "coinbase",
    defaultTopicAffinityId: "coinbase_general",
    executionMode: "coinbase",
  },
  {
    id: "gmail",
    shouldRouteFlag: "shouldRouteToGmail",
    directIntentFnKey: "isGmailDirectIntent",
    contextualFollowUpIntentFnKey: "isGmailContextualFollowUpIntent",
    shortTermFollowUpFlag: "gmailShortTermFollowUp",
    routeHint: "gmail",
    responseRoute: "gmail",
    toolCalls: ["gmail"],
    domainId: "gmail",
    resultRoute: "gmail",
    defaultTopicAffinityId: "gmail_general",
    executionMode: "gmail",
  },
  {
    id: "telegram",
    shouldRouteFlag: "shouldRouteToTelegram",
    directIntentFnKey: "isTelegramDirectIntent",
    contextualFollowUpIntentFnKey: "isTelegramContextualFollowUpIntent",
    shortTermFollowUpFlag: "telegramShortTermFollowUp",
    routeHint: "telegram",
    responseRoute: "telegram",
    toolCalls: ["telegram"],
    domainId: "telegram",
    resultRoute: "telegram",
    defaultTopicAffinityId: "telegram_general",
    executionMode: "telegram",
  },
  {
    id: "discord",
    shouldRouteFlag: "shouldRouteToDiscord",
    directIntentFnKey: "isDiscordDirectIntent",
    contextualFollowUpIntentFnKey: "isDiscordContextualFollowUpIntent",
    shortTermFollowUpFlag: "discordShortTermFollowUp",
    routeHint: "discord",
    responseRoute: "discord",
    toolCalls: ["discord"],
    domainId: "discord",
    resultRoute: "discord",
    defaultTopicAffinityId: "discord_general",
    executionMode: "discord",
  },
  {
    id: "calendar",
    shouldRouteFlag: "shouldRouteToCalendar",
    directIntentFnKey: "isCalendarDirectIntent",
    contextualFollowUpIntentFnKey: "isCalendarContextualFollowUpIntent",
    shortTermFollowUpFlag: "calendarShortTermFollowUp",
    routeHint: "calendar",
    responseRoute: "calendar",
    toolCalls: ["calendar"],
    domainId: "calendar",
    resultRoute: "calendar",
    defaultTopicAffinityId: "calendar_general",
    executionMode: "calendar",
  },
  {
    id: "reminders",
    shouldRouteFlag: "shouldRouteToReminders",
    directIntentFnKey: "isReminderDirectIntent",
    contextualFollowUpIntentFnKey: "isReminderContextualFollowUpIntent",
    shortTermFollowUpFlag: "remindersShortTermFollowUp",
    routeHint: "reminder",
    responseRoute: "reminder",
    toolCalls: ["reminder"],
    domainId: "reminders",
    resultRoute: "reminder",
    defaultTopicAffinityId: "reminder_general",
    executionMode: "reminders",
  },
  {
    id: "web_research",
    shouldRouteFlag: "shouldRouteToWebResearch",
    directIntentFnKey: "isWebResearchDirectIntent",
    contextualFollowUpIntentFnKey: "isWebResearchContextualFollowUpIntent",
    shortTermFollowUpFlag: "webResearchShortTermFollowUp",
    routeHint: "web_research",
    responseRoute: "web_research",
    toolCalls: ["web_search"],
    domainId: "web_research",
    resultRoute: "web_research",
    defaultTopicAffinityId: "web_research_general",
    executionMode: "web_research",
  },
  {
    id: "crypto",
    shouldRouteFlag: "shouldRouteToCrypto",
    directIntentFnKey: "isCryptoDirectIntent",
    contextualFollowUpIntentFnKey: "isCryptoContextualFollowUpIntent",
    shortTermFollowUpFlag: "cryptoShortTermFollowUp",
    routeHint: "crypto",
    responseRoute: "crypto",
    toolCalls: ["crypto"],
    domainId: "crypto",
    resultRoute: "crypto",
    defaultTopicAffinityId: "crypto_general",
    executionMode: "crypto",
  },
  {
    id: "market",
    shouldRouteFlag: "shouldRouteToMarket",
    directIntentFnKey: "isMarketDirectIntent",
    contextualFollowUpIntentFnKey: "isMarketContextualFollowUpIntent",
    shortTermFollowUpFlag: "marketShortTermFollowUp",
    routeHint: "market",
    responseRoute: "market",
    toolCalls: ["market"],
    domainId: "market",
    resultRoute: "market",
    defaultTopicAffinityId: "market_general",
    executionMode: "market",
  },
  {
    id: "files",
    shouldRouteFlag: "shouldRouteToFiles",
    directIntentFnKey: "isFilesDirectIntent",
    contextualFollowUpIntentFnKey: "isFilesContextualFollowUpIntent",
    shortTermFollowUpFlag: "filesShortTermFollowUp",
    routeHint: "files",
    responseRoute: "files",
    toolCalls: ["file"],
    domainId: "files",
    resultRoute: "files",
    defaultTopicAffinityId: "files_general",
    executionMode: "files",
  },
  {
    id: "memory",
    shouldRouteFlag: "shouldRouteToMemory",
    directIntentFnKey: "isMemoryDirectIntent",
    contextualFollowUpIntentFnKey: "isMemoryContextualFollowUpIntent",
    shortTermFollowUpFlag: "memoryShortTermFollowUp",
    routeHint: "memory",
    responseRoute: "memory",
    toolCalls: ["memory"],
    domainId: "memory",
    resultRoute: "memory",
    defaultTopicAffinityId: "memory_general",
    executionMode: "memory",
  },
  {
    id: "shutdown",
    shouldRouteFlag: "shouldRouteToShutdown",
    directIntentFnKey: "isShutdownDirectIntent",
    contextualFollowUpIntentFnKey: "isShutdownContextualFollowUpIntent",
    shortTermFollowUpFlag: "shutdownShortTermFollowUp",
    routeHint: "shutdown",
    responseRoute: "shutdown",
    toolCalls: ["shutdown"],
    domainId: "shutdown",
    resultRoute: "shutdown",
    defaultTopicAffinityId: "shutdown_general",
    executionMode: "shutdown",
  },
  {
    id: "diagnostics",
    shouldRouteFlag: "shouldRouteToDiagnostics",
    directIntentFnKey: "isDiagnosticsDirectIntent",
    contextualFollowUpIntentFnKey: "isDiagnosticsContextualFollowUpIntent",
    shortTermFollowUpFlag: "diagnosticsShortTermFollowUp",
    routeHint: "diagnostic",
    responseRoute: "diagnostic",
    toolCalls: ["diagnostic"],
    domainId: "diagnostics",
    resultRoute: "diagnostic",
    defaultTopicAffinityId: "diagnostics_general",
    executionMode: "diagnostics",
  },
  {
    id: "voice",
    shouldRouteFlag: "shouldRouteToVoice",
    directIntentFnKey: "isVoiceDirectIntent",
    contextualFollowUpIntentFnKey: "isVoiceContextualFollowUpIntent",
    shortTermFollowUpFlag: "voiceShortTermFollowUp",
    routeHint: "voice",
    responseRoute: "voice",
    toolCalls: ["voice"],
    domainId: "voice",
    resultRoute: "voice",
    defaultTopicAffinityId: "voice_general",
    executionMode: "voice",
  },
  {
    id: "tts",
    shouldRouteFlag: "shouldRouteToTts",
    directIntentFnKey: "isTtsDirectIntent",
    contextualFollowUpIntentFnKey: "isTtsContextualFollowUpIntent",
    shortTermFollowUpFlag: "ttsShortTermFollowUp",
    routeHint: "tts",
    responseRoute: "tts",
    toolCalls: ["tts"],
    domainId: "tts",
    resultRoute: "tts",
    defaultTopicAffinityId: "tts_general",
    executionMode: "tts",
  },
];

export function resolveOperatorLaneKeyPrefix(lane = {}) {
  return String(lane.shortTermFollowUpFlag || "").replace(/ShortTermFollowUp$/, "");
}
