import { useMemo } from "react"

import {
  OPENAI_MODEL_OPTIONS,
  GROK_MODEL_OPTIONS,
  GEMINI_MODEL_OPTIONS,
  estimateDailyCostRange,
  getClaudePriceHint,
} from "../../constants"
import type { ProviderDefinition, UseProviderDefinitionsParams } from "../types"

export function useProviderDefinitions(params: UseProviderDefinitionsParams): ProviderDefinition | null {
  const {
    settings,
    isSavingTarget,
    activeSetup,
    openaiSetupSectionRef,
    claudeSetupSectionRef,
    grokSetupSectionRef,
    geminiSetupSectionRef,
    openAISetup,
    claudeSetup,
    grokSetup,
    geminiSetup,
  } = params
  const providerDefinitions = useMemo(() => ({
    openai: {
      sectionRef: openaiSetupSectionRef,
      title: "OpenAI Setup",
      description: "Save your OpenAI credentials and model defaults for Nova API usage.",
      isConnected: settings.openai.connected,
      isSaving: isSavingTarget === "openai",
      onToggle: openAISetup.toggle,
      onSave: openAISetup.save,
      apiKey: openAISetup.apiKey,
      onApiKeyChange: openAISetup.setApiKey,
      apiKeyConfigured: openAISetup.apiKeyConfigured,
      apiKeyMasked: openAISetup.apiKeyMasked,
      baseUrl: openAISetup.baseUrl,
      onBaseUrlChange: openAISetup.setBaseUrl,
      model: openAISetup.model,
      onModelChange: openAISetup.setModel,
      modelOptions: openAISetup.modelOptions,
      apiKeyPlaceholder: "Paste your OpenAI API key here",
      apiKeyPlaceholderWhenConfigured: "Paste new OpenAI API key to replace current key",
      apiKeyInputName: "openai_token_input",
      baseUrlPlaceholder: "https://api.openai.com/v1",
      baseUrlHint: "Keep https://api.openai.com/v1 unless you are using a compatible proxy endpoint.",
      costEstimate: estimateDailyCostRange(openAISetup.model),
      priceHint: OPENAI_MODEL_OPTIONS.find((item) => item.value === openAISetup.model)?.priceHint ?? "Model pricing and output quality vary by selection.",
      usageNote: "Est. uses 20k-40k total tokens/day at a 50/50 input-output split.",
      instructionSteps: [
        "Create an API key from your OpenAI dashboard.",
        "Paste your key into API Key, then save to verify.",
        "Choose a model from the dropdown; model choice affects quality and token cost.",
      ],
    },
    claude: {
      sectionRef: claudeSetupSectionRef,
      title: "Claude Setup",
      description: "Save your Anthropic credentials and model defaults for Nova API usage.",
      isConnected: settings.claude.connected,
      isSaving: isSavingTarget === "claude",
      onToggle: claudeSetup.toggle,
      onSave: claudeSetup.save,
      apiKey: claudeSetup.apiKey,
      onApiKeyChange: claudeSetup.setApiKey,
      apiKeyConfigured: claudeSetup.apiKeyConfigured,
      apiKeyMasked: claudeSetup.apiKeyMasked,
      baseUrl: claudeSetup.baseUrl,
      onBaseUrlChange: claudeSetup.setBaseUrl,
      model: claudeSetup.model,
      onModelChange: claudeSetup.setModel,
      modelOptions: claudeSetup.modelOptions,
      apiKeyPlaceholder: "anthropic-api-key-placeholder",
      apiKeyPlaceholderWhenConfigured: "Paste new Claude API key to replace current key",
      apiKeyInputName: "claude_token_input",
      baseUrlPlaceholder: "https://api.anthropic.com",
      baseUrlHint: "Keep https://api.anthropic.com unless you are using a compatible proxy endpoint.",
      costEstimate: estimateDailyCostRange(claudeSetup.model),
      priceHint: getClaudePriceHint(claudeSetup.model),
      usageNote: "Est. uses 20k-40k total tokens/day at a 50/50 input-output split.",
      instructionSteps: [
        "Create an API key from your Anthropic dashboard.",
        "Paste your key and save to verify access.",
        "Pick an available Claude model from the dropdown and save.",
      ],
    },
    grok: {
      sectionRef: grokSetupSectionRef,
      title: "Grok Setup",
      description: "Save your xAI credentials and model defaults for Nova API usage.",
      isConnected: settings.grok.connected,
      isSaving: isSavingTarget === "grok",
      onToggle: grokSetup.toggle,
      onSave: grokSetup.save,
      apiKey: grokSetup.apiKey,
      onApiKeyChange: grokSetup.setApiKey,
      apiKeyConfigured: grokSetup.apiKeyConfigured,
      apiKeyMasked: grokSetup.apiKeyMasked,
      baseUrl: grokSetup.baseUrl,
      onBaseUrlChange: grokSetup.setBaseUrl,
      model: grokSetup.model,
      onModelChange: grokSetup.setModel,
      modelOptions: grokSetup.modelOptions,
      apiKeyPlaceholder: "xai-xxxxxxxxxxxxxxxxxxxxxxxx",
      apiKeyPlaceholderWhenConfigured: "Paste new Grok API key to replace current key",
      apiKeyInputName: "grok_token_input",
      baseUrlPlaceholder: "https://api.x.ai/v1",
      baseUrlHint: "Keep https://api.x.ai/v1 unless you are using a compatible proxy endpoint.",
      costEstimate: estimateDailyCostRange(grokSetup.model),
      priceHint: GROK_MODEL_OPTIONS.find((item) => item.value === grokSetup.model)?.priceHint ?? "Model pricing and output quality vary by selection.",
      usageNote: "Est. uses 20k-40k total tokens/day at a 50/50 input-output split.",
      instructionSteps: [
        "Create an API key from your xAI dashboard.",
        "Paste your key and save to verify access.",
        "Pick a Grok model from the dropdown and save.",
      ],
    },
    gemini: {
      sectionRef: geminiSetupSectionRef,
      title: "Gemini Setup",
      description: "Save your Gemini credentials and model defaults for Nova API usage.",
      isConnected: settings.gemini.connected,
      isSaving: isSavingTarget === "gemini",
      onToggle: geminiSetup.toggle,
      onSave: geminiSetup.save,
      apiKey: geminiSetup.apiKey,
      onApiKeyChange: geminiSetup.setApiKey,
      apiKeyConfigured: geminiSetup.apiKeyConfigured,
      apiKeyMasked: geminiSetup.apiKeyMasked,
      baseUrl: geminiSetup.baseUrl,
      onBaseUrlChange: geminiSetup.setBaseUrl,
      model: geminiSetup.model,
      onModelChange: geminiSetup.setModel,
      modelOptions: geminiSetup.modelOptions,
      apiKeyPlaceholder: "Paste Gemini API key",
      apiKeyPlaceholderWhenConfigured: "Paste new Gemini API key to replace current key",
      apiKeyInputName: "gemini_token_input",
      baseUrlPlaceholder: "https://generativelanguage.googleapis.com/v1beta/openai",
      baseUrlHint: "Keep https://generativelanguage.googleapis.com/v1beta/openai unless you are using a compatible proxy endpoint.",
      costEstimate: estimateDailyCostRange(geminiSetup.model),
      priceHint: GEMINI_MODEL_OPTIONS.find((item) => item.value === geminiSetup.model)?.priceHint ?? "Model pricing and output quality vary by selection.",
      usageNote: undefined,
      instructionSteps: [
        "Create an API key from your Google AI Studio project.",
        "Paste your key and save to verify access.",
        "Pick a Gemini model from the dropdown and save.",
      ],
    },
  }), [
    claudeSetup.apiKey,
    claudeSetup.apiKeyConfigured,
    claudeSetup.apiKeyMasked,
    claudeSetup.baseUrl,
    claudeSetup.model,
    claudeSetup.modelOptions,
    claudeSetup.save,
    claudeSetup.setApiKey,
    claudeSetup.setBaseUrl,
    claudeSetup.setModel,
    claudeSetup.toggle,
    geminiSetup.apiKey,
    geminiSetup.apiKeyConfigured,
    geminiSetup.apiKeyMasked,
    geminiSetup.baseUrl,
    geminiSetup.model,
    geminiSetup.modelOptions,
    geminiSetup.save,
    geminiSetup.setApiKey,
    geminiSetup.setBaseUrl,
    geminiSetup.setModel,
    geminiSetup.toggle,
    grokSetup.apiKey,
    grokSetup.apiKeyConfigured,
    grokSetup.apiKeyMasked,
    grokSetup.baseUrl,
    grokSetup.model,
    grokSetup.modelOptions,
    grokSetup.save,
    grokSetup.setApiKey,
    grokSetup.setBaseUrl,
    grokSetup.setModel,
    grokSetup.toggle,
    isSavingTarget,
    openAISetup.apiKey,
    openAISetup.apiKeyConfigured,
    openAISetup.apiKeyMasked,
    openAISetup.baseUrl,
    openAISetup.model,
    openAISetup.modelOptions,
    openAISetup.save,
    openAISetup.setApiKey,
    openAISetup.setBaseUrl,
    openAISetup.setModel,
    openAISetup.toggle,
    settings.claude.connected,
    settings.gemini.connected,
    settings.grok.connected,
    settings.openai.connected,
    openaiSetupSectionRef,
    claudeSetupSectionRef,
    grokSetupSectionRef,
    geminiSetupSectionRef,
  ])
  const providerKey =
    activeSetup === "openai" || activeSetup === "claude" || activeSetup === "grok" || activeSetup === "gemini"
      ? (activeSetup as "openai" | "claude" | "grok" | "gemini")
      : null
  const activeProviderDefinition = providerKey ? providerDefinitions[providerKey] : null
  return activeProviderDefinition
}
